myFashionCloset/config/routes.rb
Rails.application.routes.draw do
  
  #-----Guardarobas------
  get "/guardarobas", to: "guardarobas#index", as: "guardarobas"
  post "/guardarobas", to: "guardarobas#create" 
  get "/guardarobas/:id", to: "guardarobas#show", as: "guardaroba"
  delete "/guardarobas/:id", to: "guardarobas#destroy"
  post "guardarobas/removeOutfit/:id", to: "guardarobas#removeOutfit", as:  "guardaroba_remove_outfit"

  #------Creators--------
  get "/creators/new", to: "creators#new"
  post "/creators/new", to: "creators#create"
  get  "/creators/:id", to: "creators#show", as: :creator
  post "/creators/:id", to: "creators#accept"
  delete "creators/:id", to: "creators#destroy"
  post "/creators/:id/follow", to: "creators#follow", as: "follow_creator"
  post "creators/:id/unfollow", to: "creators#unfollow", as:"unfollow_creator"
  post "creators/:id/report", to: "creators#report"

  #-------Users----------
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get "/users/personalInfo", to: "users#personalInfo"
  put "/users/personalInfo", to: "users#personalInfoEdit"

  #-------Admin----------
  get "/admin", to: "admin#index"
  delete "/admin", to: "creators#destroy"

  #----------Capos-----------
  get "/capos", to: "capos#index", as: "capos"

  #----------Reports----------
  delete "/reports/:id", to: "reports#destroy", as: "report"


  #------Outfits---------
  get "/outfits/new", to: "outfits#new"
  post "/outfits/new", to: "outfits#create"
  post "/outfits/search", to: "outfits#search"
  get "/outfits/:id", to: "outfits#show", as: "show_outfit"
  post "/outfits/load", to: "outfits#load"  #Get via ajax new outfit to show on the homepage when scrolling down   
  post "outfits/renderHTML/:id", to: "outfits#renderHTML" #Get new loaded outfit html
  delete "/outfits/:id", to: "outfits#destroy"  
  post "outfits/addSavedOutfit", to: "outfits#addSavedOutfit" 

  #-----SearchBar------
  get "/search", to: "search#index"
  post "/search", to: "search#update"
  post "/searchoutfit", to: "search#updateoutfit"
  
  #-----Home Page--------
  root "outfits#index"

end

myFashionCloset/app/controllers/search_controller.rb
class SearchController < ApplicationController
    def index
        @query = User.joins(:creator).where("approved == true").ransack(params[:q])
        @creators = @query.result(distinct:true)
    end

    #Endpoint to research a creator without page reload (ajax)
    def update
        @query = User.joins(:creator).where("approved == true").ransack(params[:q])
        @creators = @query.result(distinct:true)
        render json:  @creators;
    end

    def updateoutfit
        @query = Outfit.ransack(params[:q])
        @outfits = @query.result(distinct:true)
        render json:  @outfits;
    end

end

myFashionCloset/app/helpers/search_helper.rb
module SearchHelper
end

myFashionCloset/app/views/search/_form.html.erb
<%= search_form_for(@query,url: search_path,method: :get) do |f| %>    <!--Search every creators_username that contains..-->
    <%= f.search_field :username_cont,placeholder: "Search creators...", id: "search-input",autocomplete: "off"%> 
    <!-- <%= f.submit "Search!", id: "search-btn"%> -->
<% end %>

myFashionCloset/app/views/search/_formoutfit.html.erb
<%= search_form_for(@query,url: searchoutfit_path,method: :get) do |f| %>    <!--Search every creators_username that contains..-->
    <%= f.search_field :username_cont,placeholder: "Search outfits...", id: "search-input-outfit",autocomplete: "off"%> 
    <!-- <%= f.submit "Search!", id: "search-btn"%> -->
<% end %>

myFashionCloset/app/views/search/index.html.erb
<html>



<body>
    <!-- Bootstrap -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>


    <!-- Style -->
    <%= stylesheet_link_tag "common.css"%>

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg  navbar-dark bg-dark">
        <a class="navbar-brand" href="#">myFashionCloset</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                    <a href="<%=root_path%>">Home</a>
                    <% if user_signed_in?%>
                    <% if !current_user.admin? %>
                        <a href="<%=capos_path%>">Items</a>
                    <%end%>
                    <% if current_user.creat? %>
                        <a href="<%=outfits_new_path%>">New Outfit</a>
                    <% elsif !current_user.admin?%>
                        <a href="<%=creators_new_path%>">Become a creator</a>
                    <%end%>
                <% end%>
            </ul>

            <% if user_signed_in? %>            <!-- IF logged show profile pic ELSE login button -->
                
                <% if current_user.avatar.attached? %>
                    <div class ="profile-pic">
                        <div class = "dropdown">
                            <a href="#" data-bs-toggle="dropdown" aria-expanded="false">
                                <% if current_user.avatar.attached? %>
                                    <img data-enlargable class = "avatar" src="<%=(url_for(current_user.avatar))%>">
                                <%else%>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="55" height="55" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                                </svg>
                                <%end%>
                            </a>

                            <ul class="dropdown-menu dropdown-menu-end">
                                <% if !current_user.admin?%>
                                    <li><a class="dropdown-item" href="<%=guardarobas_path(current_user.id)%>">Wardrobe</a></li>
                                <%end%>
                                <% if current_user.creat?%>
                                    <li><a class="dropdown-item" href="<%=creator_path(current_user.creator_id)%>">Show Profile</a></li>
                                <%end%>
                                <%- if !current_user.admin? %>
                                    <li><a class="dropdown-item" href="<%=users_personalInfo_path%>">Avatar</a></li>
                                <%end%>
                                <%if current_user.admin? %>
                                    <li><a class="dropdown-item" href="<%=admin_path(current_user.id)%>">Manage Accounts</a></li>
                                <%end%>
                                <li><%= link_to 'Log Out', destroy_user_session_path,data: {turbo_method: :delete}, class:"dropdown-item"%></li>
                            </ul>
                        </div>
                    </div>
                <%else%>
                    <div class = "profile-pic">
                        <div class ="dropdown">
                            <a href="#" data-bs-toggle="dropdown" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="55" height="55" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                                </svg>
                            </a>

                            <ul class="dropdown-menu dropdown-menu-end">
                                <% if !current_user.admin?%>
                                    <li><a class="dropdown-item" href="<%=guardarobas_path(current_user.id)%>">Wardrobe</a></li>
                                <%end%>
                                <% if current_user.creat?%>
                                    <li><a class="dropdown-item" href="<%=creator_path(current_user.creator_id)%>">Show Profile</a></li>
                                <%end%>
                                <%- if !current_user.admin? %>
                                    <li><a class="dropdown-item" href="<%=users_personalInfo_path%>">Avatar</a></li>
                                <%end%>
                                <%- if current_user.admin? %>
                                    <li><a class="dropdown-item" href="<%=admin_path(current_user.id)%>">Manage Accounts</a></li>
                                <%end%>
                                <li><%= link_to 'Log Out', destroy_user_session_path,data: {turbo_method: :delete}, class:"dropdown-item"%></li>
                            </ul>

                        </div>
                    </div>
                <%end%>
            <%else%>
                <a href="<%=new_user_session_path%>">
                    <button class = "btn btn-light login-btn">Login</button>
                </a>
            <%end%>

            <a href="<%=search_path%>" class = "search-btn">     <!-- Da rivedere -->
                <button class = "btn btn-light ">Search...
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                    </svg>
                </button>
            </a>

            
        </div>
    </nav>


</body>
</html>

<section class="gradient-custom">
<br>
<div class="container" style="display: flex; gap:10px;">
<br>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<%= javascript_include_tag "creators_search" %>
<%=stylesheet_link_tag "search" %>
<%=stylesheet_link_tag "guardaroba" %>

<div class="item">
    <h2>Enter the creator's username you are looking for!</h2>
    <%= render "search/form"%>
    <!-- 
    <%= pluralize(@creators.count, "Result") %>
    -->
    <br>

    <div class = "search-result">
        <div class = "content-header">
            <!-- <%=sort_link(@query, :username, "Creators")%> -->
        </div>  

        <div class = "content-body">
            <% @creators.each do |creator|%>
                <div class = "content-item">

                    <div class = "username-item">
                        <p><%=creator.username%></p>
                    </div>

                    <div class = "show-item">
                        <p><%=link_to "Show profile",creator_path(creator.id)%></p>
                    </div>
                
                </div>
            <%end%>
        </div>
    </div>
</div>
<br>
<br>
    <div class="item">
        <h2>Enter the outfit's name you are looking for!</h2>
        <%= render "search/formoutfit"%>
        <br>
        <div class = "search-result-outfit">
            <div class = "content-header">
                <!-- <%=sort_link(@query, :name, "Outfits")%> -->
            </div>  

            <div class = "content-body-outfit">
                
            </div>
        </div>
    </div>
</div>
</section>