myFashionCloset/config/routes.rb
Rails.application.routes.draw do
  
  #-----Guardarobas------
  get "/guardarobas", to: "guardarobas#index", as: "guardarobas"
  post "/guardarobas", to: "guardarobas#create" 
  get "/guardarobas/:id", to: "guardarobas#show", as: "guardaroba"
  delete "/guardarobas/:id", to: "guardarobas#destroy"
  post "guardarobas/removeOutfit/:id", to: "guardarobas#removeOutfit", as:  "guardaroba_remove_outfit"

  #------Creators--------
  get "/creators/new", to: "creators#new"
  post "/creators/new", to: "creators#create"
  get  "/creators/:id", to: "creators#show", as: :creator
  post "/creators/:id", to: "creators#accept"
  delete "creators/:id", to: "creators#destroy"
  post "/creators/:id/follow", to: "creators#follow", as: "follow_creator"
  post "creators/:id/unfollow", to: "creators#unfollow", as:"unfollow_creator"
  post "creators/:id/report", to: "creators#report"

  #-------Users----------
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get "/users/personalInfo", to: "users#personalInfo"
  put "/users/personalInfo", to: "users#personalInfoEdit"

  #-------Admin----------
  get "/admin", to: "admin#index"
  delete "/admin", to: "creators#destroy"

  #----------Capos-----------
  get "/capos", to: "capos#index", as: "capos"

  #----------Reports----------
  delete "/reports/:id", to: "reports#destroy", as: "report"


  #------Outfits---------
  get "/outfits/new", to: "outfits#new"
  post "/outfits/new", to: "outfits#create"
  post "/outfits/search", to: "outfits#search"
  get "/outfits/:id", to: "outfits#show", as: "show_outfit"
  post "/outfits/load", to: "outfits#load"  #Get via ajax new outfit to show on the homepage when scrolling down   
  post "outfits/renderHTML/:id", to: "outfits#renderHTML" #Get new loaded outfit html
  delete "/outfits/:id", to: "outfits#destroy"  
  post "outfits/addSavedOutfit", to: "outfits#addSavedOutfit" 

  #-----SearchBar------
  get "/search", to: "search#index"
  post "/search", to: "search#update"
  post "/searchoutfit", to: "search#updateoutfit"
  
  #-----Home Page--------
  root "outfits#index"

end

myFashionCloset/app/models/creator.rb
class Creator < ApplicationRecord
    belongs_to :user
    has_many :outfits, dependent: :destroy
    has_many :follows, dependent: :destroy
    has_many :followingUsers, through: :follows, source: :user, dependent: :destroy
    has_many :reports, dependent: :destroy
end

myFashionCloset/app/controllers/creators_controller.rb
class CreatorsController < ApplicationController
  #before_action :set_creator, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:show]
  skip_before_action :verify_authenticity_token


  # GET /creators or /creators.json
  def index
    @creators = Creator.all
  end

  # GET /creators/1 or /creators/1.json
  def show
    begin
      @creator = Creator.find(params[:id])

      if @creator.approved == nil
        flash[:alert] = "Searched creator doesn't exist"
        redirect_to root_path
      end

      if(current_user!=nil)
        @current_user = current_user
        @user = User.where("creator_id = ?",params[:id])[0]   #Getting creator' info
        @outfits = @creator.outfits.order(created_at: :desc);      #Getting creator' outfit
        @followed = !(@creator.follows.where("user_id = ?",@current_user.id).empty?)
      
      else
        @user = User.where("creator_id = ?",params[:id])[0]   #Getting creator' info
        @outfits = @creator.outfits.order(created_at: :desc);      #Getting creator' outfit
      end

    rescue => exception   #Doesn't exits
      flash[:alert] = "Searched creator doesn't exist"
      redirect_to root_path
    end
    
  end

  # GET /creators/new
  def new
    @user = current_user
    if @user.creat == false #Bisogna introdurre una gestione più accurata (Richiesta rifiutata,richiesta accettata etc)
      flash[:alert] = "Your request was refused because the description is not exhaustive or it does not comply with the site policy"
      redirect_to root_path
    elsif @user.creator_id != nil   #Bisogna introdurre una gestione più accurata (Richiesta rifiutata,richiesta accettata etc)
      flash[:alert] = "A request to become a creator has already been sent"
      redirect_to root_path
    else
      @creator = Creator.new
    end
  end

  # GET /creators/1/edit
  def edit
  end

  # POST /creators or /creators.json
  def create
    @creator = Creator.new(creator_params)
    @user = current_user

    @creator.approved = nil  #Admin must accept/deny(true/false) new creators
    @creator.user_id = @user.id
    
    if @creator.save
      flash[:success] = "Request sent correctly"
      @user.update(creator_id: @creator.id)
      #format.html { redirect_to creator_url(@creator), notice: "Creator was successfully created." }
      #format.json { render :show, status: :created, location: @creator }
    else
      flash[:alert] = "Something gone wrong!"
      #format.html { render :new, status: :unprocessable_entity }
      #format.json { render json: @creator.errors, status: :unprocessable_entity }
    end
    redirect_to root_path
    
  end

  # PATCH/PUT /creators/1 or /creators/1.json
  def update
    respond_to do |format|
      if @creator.update(creator_params)
        format.html { redirect_to creator_url(@creator), notice: "Creator was successfully updated." }
        format.json { render :show, status: :ok, location: @creator }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @creator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /creators/1 or /creators/1.json
  def destroy
    @creator = Creator.find(params[:id])
    authorize! :destroy, @creator, :message => "BEWARE: you are not
    authorized to delete creators"

    if @creator.present?
        @creator.destroy
    end

    @user = User.where(id: @creator.user_id)[0]
    @user.creator_id = nil;
    @user.creat = false;
    @user.save!

    respond_to do |format|
      format.html { redirect_to admin_url, success: "Creator was successfully deleted." }
      format.json { head :no_content }
    end
  end

  #A user follow a new creator
  def follow
    @creator = Creator.find(params[:id])
    @user = current_user
    @follow = Follow.new(user_id: @user.id,creator_id: @creator.id)
    @follow.save!
  end

  #user unfollow a creator
  def unfollow
    @creator = Creator.find(params[:id])
    @user = current_user
    Follow.where("creator_id = ? and user_id = ?",@creator.id,@user.id).destroy_all
  end

  #user reported a creator
  def report
    @creator = Creator.find(params[:id])
    @user = current_user
    @report = Report.new(about: params[:about],description: params[:description],user_id: @user.id, creator_id: @creator.id)
    if @report.save!    #Da rivedere
      "ok"
    else
      "ko"
    end

  end

  #POST accettazione creator da parte dell'admin
  def accept
    @creator = Creator.find(params[:id])
    @creator.approved = true
    @creator.save!

    @user = User.where(id: @creator.user_id)[0]
    @user.creat = true
    @user.save!

    respond_to do |format|
      format.html { redirect_to admin_url, success: "Creator was successfully accepted." }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_creator
      @creator = Creator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def creator_params
      params.require(:creator).permit(:firstName, :lastName, :birthday, :gender, :styleDesc, :approved)
    end


end

myFashionCloset/app/helpers/creators_helper.rb
module CreatorsHelper
end

myFashionCloset/app/views/creators/edit.html.erb
<h1>Editing creator</h1>

<%= render "form", creator: @creator %>

<br>

<div>
  <%= link_to "Show this creator", @creator %> |
  <%= link_to "Back to creators", creators_path %>
</div>

myFashionCloset/app/views/creators/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Creators</h1>

<div id="creators">
  <% @creators.each do |creator| %>
    <%= render creator %>
    <p>
      <%= link_to "Show this creator", creator %>
    </p>
  <% end %>
</div>

<%= link_to "New creator", new_creator_path %>

myFashionCloset/app/views/creators/new.html.erb
<html>



<body>
    <!-- Bootstrap -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>


    <!-- Style -->
    <%= stylesheet_link_tag "common.css"%>

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg  navbar-dark bg-dark">
        <a class="navbar-brand" href="#">myFashionCloset</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <% if user_signed_in?%>
                    <a href="<%=root_path%>">Home</a>
                    <% if !current_user.admin? %>
                        <a href="<%=capos_path%>">Items</a>
                    <%end%>
                    <% if current_user.creat? %>
                        <a href="<%=outfits_new_path%>">New Outfit</a>
                    <% elsif !current_user.admin?%>
                        <a href="<%=creators_new_path%>">Become a creator</a>
                    <%end%>
                <% end%>
            </ul>

            <% if user_signed_in? %>            <!-- IF logged show profile pic ELSE login button -->
                
                <% if current_user.avatar.attached? %>
                    <div class ="profile-pic">
                        <div class = "dropdown">
                            <a href="#" data-bs-toggle="dropdown" aria-expanded="false">
                                <% if @user.avatar.attached? %>
                                    <img data-enlargable class = "avatar" src="<%=(url_for(@user.avatar))%>">
                                <%else%>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="55" height="55" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                                    </svg>
                                <%end%>
                            </a>

                            <ul class="dropdown-menu dropdown-menu-end">
                                <% if !current_user.admin?%>
                                    <li><a class="dropdown-item" href="<%=guardarobas_path(current_user.id)%>">Wardrobe</a></li>
                                <%end%>
                                <% if current_user.creat?%>
                                    <li><a class="dropdown-item" href="<%=creator_path(current_user.creator_id)%>">Show Profile</a></li>
                                <%end%>
                                <%- if !current_user.admin? %>
                                    <li><a class="dropdown-item" href="<%=users_personalInfo_path%>">Avatar</a></li>
                                <%end%>
                                <%if current_user.admin? %>
                                    <li><a class="dropdown-item" href="<%=admin_path(current_user.id)%>">Manage Accounts</a></li>
                                <%end%>
                                <li><%= link_to 'Log Out', destroy_user_session_path,data: {turbo_method: :delete}, class:"dropdown-item"%></li>
                            </ul>
                        </div>
                    </div>
                <%else%>
                    <div class = "profile-pic">
                        <div class ="dropdown">
                            <a href="#" data-bs-toggle="dropdown" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="55" height="55" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                                </svg>
                            </a>

                            <ul class="dropdown-menu dropdown-menu-end">
                                <% if !current_user.admin?%>
                                    <li><a class="dropdown-item" href="<%=guardarobas_path(current_user.id)%>">Wardrobe</a></li>
                                <%end%>
                                <% if current_user.creat?%>
                                    <li><a class="dropdown-item" href="<%=creator_path(current_user.creator_id)%>">Show Profile</a></li>
                                <%end%>
                                <%- if !current_user.admin? %>
                                    <li><a class="dropdown-item" href="<%=users_personalInfo_path%>">Avatar</a></li>
                                <%end%>
                                <%- if current_user.admin? %>
                                    <li><a class="dropdown-item" href="<%=admin_path(current_user.id)%>">Manage Accounts</a></li>
                                <%end%>
                                <li><%= link_to 'Log Out', destroy_user_session_path,data: {turbo_method: :delete}, class:"dropdown-item"%></li>
                            </ul>

                        </div>
                    </div>
                <%end%>
            <%else%>
                <a href="<%=new_user_session_path%>">
                    <button class = "btn btn-light login-btn">Login</button>
                </a>
            <%end%>

            <a href="<%=search_path%>" class = "search-btn">     <!-- Da rivedere -->
                <button class = "btn btn-light ">Search...
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                    </svg>
                </button>
            </a>

            
        </div>
    </nav>


</body>
</html>

<div class="testo-centrato">
<br>
<h2>Become a creator!</h2>
</div>

<%= render "form", creator: @creator %>

myFashionCloset/app/views/creators/show.html.erb
<!-- Bootstrap -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


<!-- Javascript -->
<%= javascript_include_tag "creator_show" %>


<!-- Style -->
<%= stylesheet_link_tag "common.css"%>
<%= stylesheet_link_tag "creator/show.css"%>

<p style="color: green"><%= notice %></p>
<!-- <%= render @creator %> -->

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg  navbar-dark bg-dark">
        <a class="navbar-brand" href="#">myFashionCloset</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">            
                    <a href="<%=root_path%>">Home</a>
                    <% if user_signed_in?%>
                    <% if !current_user.admin? %>
                        <a href="<%=capos_path%>">Items</a>
                    <%end%>
                    <% if current_user.creat? %>
                        <a href="<%=outfits_new_path%>">New Outfit</a>
                    <% elsif !current_user.admin?%>
                        <a href="<%=creators_new_path%>">Become a creator</a>
                    <%end%>
                <% end%>
            </ul>

            <% if user_signed_in? %>            <!-- IF logged show profile pic ELSE login button -->
                
                <% if current_user.avatar.attached? %>
                    <div class ="profile-pic">
                        <div class = "dropdown">
                            <a href="#" data-bs-toggle="dropdown" aria-expanded="false">
                                <% if @user.avatar.attached? %>
                                    <img data-enlargable class = "avatar" src="<%=(url_for(current_user.avatar))%>">
                                <%else%>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="55" height="55" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                                </svg>
                                <%end%>
                            </a>

                            <ul class="dropdown-menu dropdown-menu-end">
                                <% if !current_user.admin?%>
                                    <li><a class="dropdown-item" href="<%=guardarobas_path(current_user.id)%>">Wardrobe</a></li>
                                <%end%>
                                <% if current_user.creat?%>
                                    <li><a class="dropdown-item" href="<%=creator_path(current_user.creator_id)%>">Show Profile</a></li>
                                <%end%>
                                <%- if !current_user.admin? %>
                                    <li><a class="dropdown-item" href="<%=users_personalInfo_path%>">Avatar</a></li>
                                <%end%>
                                <%if current_user.admin? %>
                                    <li><a class="dropdown-item" href="<%=admin_path(current_user.id)%>">Manage Accounts</a></li>
                                <%end%>
                                <li><%= link_to 'Log Out', destroy_user_session_path,data: {turbo_method: :delete}, class:"dropdown-item"%></li>
                            </ul>
                        </div>
                    </div>
                <%else%>
                    <div class = "profile-pic">
                        <div class ="dropdown">
                            <a href="#" data-bs-toggle="dropdown" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="55" height="55" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                                </svg>
                            </a>

                            <ul class="dropdown-menu dropdown-menu-end">
                                <% if !current_user.admin?%>
                                    <li><a class="dropdown-item" href="<%=guardarobas_path(current_user.id)%>">Wardrobe</a></li>
                                <%end%>
                                <% if current_user.creat?%>
                                    <li><a class="dropdown-item" href="<%=creator_path(current_user.creator_id)%>">Show Profile</a></li>
                                <%end%>
                                <%- if !current_user.admin? %>
                                    <li><a class="dropdown-item" href="<%=users_personalInfo_path%>">Avatar</a></li>
                                <%end%>
                                <%- if current_user.admin? %>
                                    <li><a class="dropdown-item" href="<%=admin_path(current_user.id)%>">Manage Accounts</a></li>
                                <%end%>
                                <li><%= link_to 'Log Out', destroy_user_session_path,data: {turbo_method: :delete}, class:"dropdown-item"%></li>
                            </ul>

                        </div>
                    </div>
                <%end%>
            <%else%>
                <a href="<%=new_user_session_path%>">
                    <button class = "btn btn-light login-btn">Login</button>
                </a>
            <%end%>

            <a href="<%=search_path%>" class = "search-btn">     <!-- Da rivedere -->
                <button class = "btn btn-light ">Search...
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                    </svg>
                </button>
            </a>

            
        </div>
    </nav>

<div class = "main">
  <br>
    <div class = "main-header">
        <div class = "creator-info">

            <div class ="profile-pic">
              <input type="checkbox" id="zoomCheck">
                <label for="zoomCheck">
                    <% if @user.avatar.attached? %>
                        <img data-enlargable class = "avatar" src="<%=(url_for(@user.avatar))%>">
                    <%else%>
                        <svg xmlns="http://www.w3.org/2000/svg" width="55" height="55" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                        </svg>
                    <%end%>
                </label>
            </div>

            <div class = "personal-info">
                <div class = "info-element">
                      <p>
                        <strong><%= @creator.firstName %> <%= @creator.lastName %></strong>
                    </p>
                </div>

                <div class = "info-element">
                      <p>
                        <%= @creator.styleDesc %>
                    </p>
                </div>

            </div>
          </div>

          <div class = "creator-username">
            <h3><%=@user.username%>'s outfits&nbsp;&nbsp;</h3>
          </div>

          <div class = "creator-action" id= "<%=@creator.id%>">
            <% if @current_user!=nil && @current_user.id != @creator.user_id && !@current_user.admin?%>
              <% if @followed%>
                  <button id ="unfollow-btn"  class = "btn btn-secondary" >Unfollow</button>
                  <button id ="follow-btn" class = "btn btn-secondary" style = "display:none">Follow</button>

              <%else %>
                  <button id ="unfollow-btn" class = "btn btn-secondary" style = "display:none">Unfollow</button>
                  <button id ="follow-btn" class = "btn btn-secondary" >Follow</button>
              <%end%>
            <%else %>
            <%end%>
            <%if user_signed_in? && !current_user.admin? && current_user.creator_id != @creator.id%>
              &nbsp;&nbsp;<button  data-toggle="modal" data-target="#modalReport" class = "btn btn-danger">Report</button>
            <%end%>
          </div>
        

    </div>

    <div class = "main-content">
        <% @outfits.each do |outfit|%>
            <div class = "outfit">
              <div class = "outfit-carousel">
                <div id = "carousel<%=outfit.id%>" class = "carousel slide" data-ride="carousel">
                    <div class = "carousel-inner">
                      <% outfit.capos.each_with_index do |capo,index| %>
                          <div class = "carousel-item <%="active" if index == 0%>">

                              <img class="d-block w-150" src = <%=url_for(capo.immagine)%>>
                              <div class="carousel-caption d-none d-md-block">
                                <div class="testo-bordato">
                                  <h6><%=capo.nome%></h6>
                                </div>
                              </div>

                          </div>
                      <%end%>
                  </div>

                  <a class="carousel-control-prev" href="#carousel<%=outfit.id%>" role="button" data-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="sr-only">Previous</span>
                  </a>
                  <a class="carousel-control-next" href="#carousel<%=outfit.id%>" role="button" data-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="sr-only">Next</span>
                  </a>
                </div>
              </div>

              <div class = "outfit-info">
                <h4 class = "outfit-name"><%=outfit.name%></h4>
                <p class = "outfit-description"><%=outfit.description%></p>
                <a href = "<%=show_outfit_path(outfit.id)%>">Show</a>
              </div>

            </div>
        <%end%>
    </div>
</div>



<!--Report Modal -->
<div class="modal fade" id="modalReport" tabindex="-1" role="dialog" aria-labelledby="modalReportTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalReportTitle">Report</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
            <div class = "form-item">
                <input type = "text" id ="inputAbout" placeholder="About" required>
            </div>
            <br>
            <div class = "form-item">
                <input type ="text" id = "inputDescription" placeholder ="Description" required>
            </div>

        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id = "report-btn">Report!</button>
      </div>
    </div>
  </div>
</div>