myFashionCloset/config/routes.rb
Rails.application.routes.draw do
  
  #-----Guardarobas------
  get "/guardarobas", to: "guardarobas#index", as: "guardarobas"
  post "/guardarobas", to: "guardarobas#create" 
  get "/guardarobas/:id", to: "guardarobas#show", as: "guardaroba"
  delete "/guardarobas/:id", to: "guardarobas#destroy"
  post "guardarobas/removeOutfit/:id", to: "guardarobas#removeOutfit", as:  "guardaroba_remove_outfit"

  #------Creators--------
  get "/creators/new", to: "creators#new"
  post "/creators/new", to: "creators#create"
  get  "/creators/:id", to: "creators#show", as: :creator
  post "/creators/:id", to: "creators#accept"
  delete "creators/:id", to: "creators#destroy"
  post "/creators/:id/follow", to: "creators#follow", as: "follow_creator"
  post "creators/:id/unfollow", to: "creators#unfollow", as:"unfollow_creator"
  post "creators/:id/report", to: "creators#report"

  #-------Users----------
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get "/users/personalInfo", to: "users#personalInfo"
  put "/users/personalInfo", to: "users#personalInfoEdit"

  #-------Admin----------
  get "/admin", to: "admin#index"
  delete "/admin", to: "creators#destroy"

  #----------Capos-----------
  get "/capos", to: "capos#index", as: "capos"

  #----------Reports----------
  delete "/reports/:id", to: "reports#destroy", as: "report"


  #------Outfits---------
  get "/outfits/new", to: "outfits#new"
  post "/outfits/new", to: "outfits#create"
  post "/outfits/search", to: "outfits#search"
  get "/outfits/:id", to: "outfits#show", as: "show_outfit"
  post "/outfits/load", to: "outfits#load"  #Get via ajax new outfit to show on the homepage when scrolling down   
  post "outfits/renderHTML/:id", to: "outfits#renderHTML" #Get new loaded outfit html
  delete "/outfits/:id", to: "outfits#destroy"  
  post "outfits/addSavedOutfit", to: "outfits#addSavedOutfit" 

  #-----SearchBar------
  get "/search", to: "search#index"
  post "/search", to: "search#update"
  post "/searchoutfit", to: "search#updateoutfit"
  
  #-----Home Page--------
  root "outfits#index"

end

myFashionCloset/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    if user.admin?
      cannot :read, Capo
      cannot :manage, Guardaroba
      can [:read, :create, :destroy], Creator
      can [:read, :destroy], Outfit
      cannot [:create], Outfit
      can [:destroy], Report
      can :manage, Admin
    elsif user.creat?
      can :read, Capo
      can [:read, :create, :destroy], Guardaroba
      can [:read, :Create], Creator
      cannot :destroy, Creator
      can [:read, :create], Outfit
      cannot [:destroy], Outfit
      can :create, Report
      cannot :destroy, Report
      cannot :manage, Admin
    else
      can :read, Capo
      can [:read, :create, :destroy], Guardaroba
      can [:read, :create], Creator
      cannot :destroy, Creator
      can :read, Outfit
      cannot [:create, :destroy], Outfit
      can :create, Report
      cannot :destroy, Report
      cannot :manage, Admin
    end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

myFashionCloset/app/models/admin.rb
class Admin < ApplicationRecord
end

myFashionCloset/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

myFashionCloset/app/models/capo.rb
class Capo < ApplicationRecord
    has_and_belongs_to_many :outfits
end

myFashionCloset/app/models/creator.rb
class Creator < ApplicationRecord
    belongs_to :user
    has_many :outfits, dependent: :destroy
    has_many :follows, dependent: :destroy
    has_many :followingUsers, through: :follows, source: :user, dependent: :destroy
    has_many :reports, dependent: :destroy
end

myFashionCloset/app/models/follow.rb
class Follow < ApplicationRecord
    belongs_to :user
    belongs_to :creator
end

myFashionCloset/app/models/guardaroba.rb
class Guardaroba < ApplicationRecord
    belongs_to :user
    has_many :capos
end

myFashionCloset/app/models/outfit.rb
class Outfit < ApplicationRecord
    belongs_to :creator
    has_and_belongs_to_many :capos
    has_many :savedOutfits
end

myFashionCloset/app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  belongs_to :creator
end

myFashionCloset/app/models/saved_outfit.rb
class SavedOutfit < ApplicationRecord
    belongs_to :user
    belongs_to :outfit
end

myFashionCloset/app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar        #profilePic
  has_one :creator                #Non completamente vero
  has_many :follows
  has_many :followedCreators, through: :follows, source: :creator
  has_many :reports
  has_many :savedOutfits
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]
  
  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    # Uncomment the section below if you want users to be created if they don't exist
     unless user
         user = User.create(username: data['email'],
            email: data['email'],
            password: Devise.friendly_token[0,20]
         )
     end
    user
  end
  
end

myFashionCloset/app/controllers/admin_controller.rb
class AdminController < ApplicationController
    
    def index
        @creators = Creator.all
        authorize! :read, Admin, :message => "BEWARE: you are not
        authorized to access this page"

        @outfits = Outfit.all
        @reports = Report.all
    end

end

myFashionCloset/app/controllers/capos_controller.rb
class CaposController < ApplicationController
  before_action :authenticate_user!

  # GET /capos or /capos.json
  def index
    authorize! :read, Capo, :message => "BEWARE: you are not
        authorized to access this page"
    if Articolo.save_top_popular_articles
      @message = 'Succeed'
    else
      @message = 'Failed'
    end
    @q = Capo.ransack(params[:q])
    #@capos = Capo.all
    @capos = @q.result(distinct: true)
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_capo
      @capo = Capo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def capo_params
      params.require(:capo).permit(:immagine, :nome, :descrizione)
    end       
      
end

myFashionCloset/app/helpers/application_helper.rb
module ApplicationHelper

    def flash_class(level)              #Used to get bootstrap alert class from flash alert class
        bootstrap_alert_class = {
          "success" => "alert-success",
          "error" => "alert-danger",
          "notice" => "alert-info",
          "alert" => "alert-danger",
          "warn" => "alert-warning"
        }
        bootstrap_alert_class[level]
      end

end

myFashionCloset/app/helpers/capos_helper.rb
module CaposHelper
end

myFashionCloset/app/helpers/creators_helper.rb
module CreatorsHelper
end

myFashionCloset/app/helpers/guardarobas_helper.rb
module GuardarobasHelper
end

myFashionCloset/app/helpers/outfits_helper.rb
module OutfitsHelper
end

myFashionCloset/app/helpers/search_helper.rb
module SearchHelper
end

myFashionCloset/app/helpers/users_helper.rb
module UsersHelper
end

myFashionCloset/app/views/admin/index.html.erb
<html>



<body>
    <!-- Bootstrap -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Style -->
    <%= stylesheet_link_tag "common.css"%>
    <%= stylesheet_link_tag "guardaroba.css"%>

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg  navbar-dark bg-dark">
        <a class="navbar-brand" href="#">myFashionCloset</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <% if user_signed_in?%>
                    <a href="<%=root_path%>">Home</a>
                <%end%>
            </ul>

            <% if user_signed_in? %>            <!-- IF logged show profile pic ELSE login button -->
                
                <% if current_user.avatar.attached? %>
                    <div class ="profile-pic">
                        <div class = "dropdown">
                            <a href="#" data-bs-toggle="dropdown" aria-expanded="false">
                                <% if current_user.avatar.attached? %>
                                    <img data-enlargable class = "avatar" src="<%=(url_for(current_user.avatar))%>">
                                <%else%>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="55" height="55" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                                </svg>
                                <%end%>
                            </a>

                            <ul class="dropdown-menu dropdown-menu-end">
                                <%- if !current_user.admin? %>
                                    <li><a class="dropdown-item" href="<%=guardarobas_path(current_user.id)%>">Wardrobe</a></li>
                                    <li><a class="dropdown-item" href="#">Show Profile</a></li>
                                    <li><a class="dropdown-item" href="<%=users_personalInfo_path%>">Avatar</a></li>
                                <%end%>
                                <%- if current_user.admin? %>
                                    <li><a class="dropdown-item" href="<%=admin_path(current_user.id)%>">Manage Accounts</a></li>
                                <%end%>
                                <li><%= link_to 'Log Out', destroy_user_session_path,data: {turbo_method: :delete}, class:"dropdown-item"%></li>
                            </ul>
                        </div>
                    </div>
                <%else%>
                    <div class = "profile-pic">
                        <div class ="dropdown">
                            <a href="#" data-bs-toggle="dropdown" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="55" height="55" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                                </svg>
                            </a>

                            <ul class="dropdown-menu dropdown-menu-end">
                                <%- if !current_user.admin? %>
                                    <li><a class="dropdown-item" href="<%=guardarobas_path(current_user.id)%>">Wardrobe</a></li>
                                    <li><a class="dropdown-item" href="#">Show Profile</a></li> 
                                    <li><a class="dropdown-item" href="<%=users_personalInfo_path%>">Avatar</a></li>
                                <%end%>
                                <%- if current_user.admin? %>
                                    <li><a class="dropdown-item" href="<%=admin_path(current_user.id)%>">Manage Accounts</a></li>
                                <%end%>
                                <li><%= link_to 'Log Out', destroy_user_session_path,data: {turbo_method: :delete}, class:"dropdown-item"%></li>
                            </ul>

                        </div>
                    </div>
                <%end%>
            <%else%>
                <a href="<%=new_user_session_path%>">
                    <button class = "btn btn-light login-btn">Login</button>
                </a>
            <%end%>

            <a href="<%=search_path%>" class = "search-btn">     <!-- Da rivedere -->
                <button class = "btn btn-light ">Search...
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                    </svg>
                </button>
            </a>

            
        </div>
    </nav>


</body>
</html>


<div class="container">
  <div class="row justify-content-around">
    <div class="col-4">
<br>
<h1>Manage creators</h1>
<br>

<div id="creators">
  <% @creators.each do |creator| %>
    <% if creator.approved == true %>
    <%= render creator %>
      <table><tr><td><%= button_to "Remove", creator, method: :delete, class: "btn btn-warning" %></td><tr></table>
    <% end %>
    <br>
    <br>
  <% end %> 
  <h2>New creators requests</h2>
  <% @creators.each do |creator| %>
    <% if creator.approved == nil %>
    <%= render creator %>
      <table><tr><td><%= button_to "Accept", creator, method: :accept, class: "btn btn-success" %></td><td><%= button_to "Decline", creator, method: :delete,  class: "btn btn-danger"%></td></tr></table>
    <% end %>
    <br>
   <% end %> 
</div>
</div>

<div class="col-4">
<br>
<h1>Manage outfits</h1>
<br>
<div class = "outfits">
    <table>
    <% @outfits.each do |outfit|%>
        <tr><td><%=link_to "#{outfit.name} by #{User.where(creator_id: outfit.creator_id)[0].username}", show_outfit_path(outfit.id)%>&nbsp;&nbsp;&nbsp;</td><td><%= button_to "Remove", show_outfit_path(outfit.id), method: :delete, class: "btn btn-warning" %></td></tr>
    <%end%>
    </table>
</div>
<br>
<br>

<h1>Manage reports</h1>
<br>
<div id="reports">
    <% @reports.each_with_index do |report,index|%>
         <h5>Report from: <%= "#{User.where(id: report.user_id)[0].username}" %></h5>
         <h5>Creator: <%=link_to "#{User.where(creator_id: report.creator_id)[0].username}", creator_path(report.creator_id)%></h5>
         <h5>Description: <%= "#{report.description}" %></h5>
         <table><tr><td><button  data-toggle="modal" data-target="#modalRep<%=index.to_s%>" class = "btn btn-success">Accept</button></td><td><%= button_to "Decline", report_path(report.id), method: :delete, class: 'btn btn-danger'%></td><tr></table>
         <br>
         <br>

         <!--Report Modal -->
<div class="modal fade" id="modalRep<%=index.to_s%>" tabindex="-1" role="dialog" aria-labelledby="modalRepTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalRepTitle">Report</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete the creator <b><%="#{User.where(creator_id: report.creator_id)[0].username}"%></b>?
      </div>
      <div class="modal-footer">
        <%= button_to "Yes", Creator.where(id: report.creator_id)[0], method: :delete, class: "btn btn-secondary"%>
        <button type="button" class="btn btn-primary" id = "report-btn">No</button>
      </div>
    </div>
  </div>
</div>
    <%end%>
</div>
</div>
</div>
</div>

myFashionCloset/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyFashionCloset</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <!-- <%= javascript_importmap_tags %> -->
  </head>

  <body>
  <section class="gradient-custom" style="display:flex;flex-direction:column">
  
  <!-- Alert message-->
  <div class="div-alert">
    <% flash.each do |key, message| %>
      <div class="alert <%= flash_class(key) %> alert-dismissible fade show text-center" role="alert">
        <%= message %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
  </div>


    <%= yield %>

  </section>
  </body>
</html>

 