myFashionCloset/config/routes.rb
Rails.application.routes.draw do
  
  #-----Guardarobas------
  get "/guardarobas", to: "guardarobas#index", as: "guardarobas"
  post "/guardarobas", to: "guardarobas#create" 
  get "/guardarobas/:id", to: "guardarobas#show", as: "guardaroba"
  delete "/guardarobas/:id", to: "guardarobas#destroy"
  post "guardarobas/removeOutfit/:id", to: "guardarobas#removeOutfit", as:  "guardaroba_remove_outfit"

  #------Creators--------
  get "/creators/new", to: "creators#new"
  post "/creators/new", to: "creators#create"
  get  "/creators/:id", to: "creators#show", as: :creator
  post "/creators/:id", to: "creators#accept"
  delete "creators/:id", to: "creators#destroy"
  post "/creators/:id/follow", to: "creators#follow", as: "follow_creator"
  post "creators/:id/unfollow", to: "creators#unfollow", as:"unfollow_creator"
  post "creators/:id/report", to: "creators#report"

  #-------Users----------
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get "/users/personalInfo", to: "users#personalInfo"
  put "/users/personalInfo", to: "users#personalInfoEdit"

  #-------Admin----------
  get "/admin", to: "admin#index"
  delete "/admin", to: "creators#destroy"

  #----------Capos-----------
  get "/capos", to: "capos#index", as: "capos"

  #----------Reports----------
  delete "/reports/:id", to: "reports#destroy", as: "report"


  #------Outfits---------
  get "/outfits/new", to: "outfits#new"
  post "/outfits/new", to: "outfits#create"
  post "/outfits/search", to: "outfits#search"
  get "/outfits/:id", to: "outfits#show", as: "show_outfit"
  post "/outfits/load", to: "outfits#load"  #Get via ajax new outfit to show on the homepage when scrolling down   
  post "outfits/renderHTML/:id", to: "outfits#renderHTML" #Get new loaded outfit html
  delete "/outfits/:id", to: "outfits#destroy"  
  post "outfits/addSavedOutfit", to: "outfits#addSavedOutfit" 

  #-----SearchBar------
  get "/search", to: "search#index"
  post "/search", to: "search#update"
  post "/searchoutfit", to: "search#updateoutfit"
  
  #-----Home Page--------
  root "outfits#index"

end

myFashionCloset/app/models/guardaroba.rb
class Guardaroba < ApplicationRecord
    belongs_to :user
    has_many :capos
end

myFashionCloset/app/controllers/guardarobas_controller.rb
class GuardarobasController < ApplicationController
  before_action :authenticate_user!
  before_action :set_guardaroba, only: %i[ show destroy ]

  # GET /guardarobas or /guardarobas.json
  def index
   @guardarobas = Guardaroba.where(user_id: current_user.id)
   

   @savedOutfits = SavedOutfit.where(user_id: current_user.id)
   @outfitIds = []
   @savedOutfits.each do |s| 
     @outfitIds.push(s.outfit_id)
   end
   
   @user = current_user
   @outfits = Outfit.where(id:@outfitIds)
   authorize! :read, Guardaroba, :message => "BEWARE: you are not
        authorized to access this page"
   

  end

  # GET /guardarobas/1 or /guardarobas/1.json
  def show
  end

  # POST /guardarobas or /guardarobas.json
  def create
    Wardrobe.add_to_wardrobe(Capo.find(params[:id]), current_user.id)
  end

  def removeOutfit
    @savedOutfit = SavedOutfit.where("outfit_id = ? and user_id = ?",params[:id],current_user.id)
    @savedOutfit.destroy_all 

    respond_to do |format|
      format.html { redirect_to guardarobas_url, success: "Guardaroba was successfully destroyed." }
      format.json { head :no_content }
    end

  end

  # DELETE /guardarobas/1 or /guardarobas/1.json
  def destroy
    @guardaroba.destroy

    respond_to do |format|
      format.html { redirect_to guardarobas_url, notice: "This item has been removed from your wardrobe." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guardaroba
      @guardaroba = Guardaroba.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def guardaroba_params
      params.require(:guardaroba).permit(:user_id, :immagine_capo, :nome_capo)
    end
end

myFashionCloset/app/helpers/guardarobas_helper.rb
module GuardarobasHelper
end

myFashionCloset/app/views/guardarobas/_guardaroba.html.erb
<div id="<%= dom_id guardaroba %>">
  <p>
    <strong>User:</strong>
    <%= guardaroba.user_id %>
  </p>

  <p>
    <strong>Immagine capo:</strong>
    <%= guardaroba.immagine_capo %>
  </p>

  <p>
    <strong>Nome capo:</strong>
    <%= guardaroba.nome_capo %>
  </p>

</div>

myFashionCloset/app/views/guardarobas/index.html.erb
<html>



<body>
    <!-- Bootstrap -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

     <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Style -->
    <%= stylesheet_link_tag "common.css"%>
    <%= stylesheet_link_tag "guardaroba.css"%>

    <!-- My Script -->
    <%= javascript_include_tag "utils"%>
    <%= javascript_include_tag "guardaroba"%>

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg  navbar-dark bg-dark">
        <a class="navbar-brand" href="#">myFashionCloset</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <% if user_signed_in?%>
                    <a href="<%=root_path%>">Home</a>
                    <% if !current_user.admin? %>
                        <a href="<%=capos_path%>">Items</a>
                    <%end%>
                    <% if current_user.creat? %>
                        <a href="<%=outfits_new_path%>">New Outfit</a>
                    <% elsif !current_user.admin?%>
                        <a href="<%=creators_new_path%>">Become a creator</a>
                    <%end%>
                <% end%>
            </ul>

            <% if user_signed_in? %>            <!-- IF logged show profile pic ELSE login button -->
                
                <% if current_user.avatar.attached? %>
                    <div class ="profile-pic">
                        <div class = "dropdown">
                            <a href="#" data-bs-toggle="dropdown" aria-expanded="false">
                                <% if @user.avatar.attached? %>
                                    <img data-enlargable class = "avatar" src="<%=(url_for(current_user.avatar))%>">
                                <%else%>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="55" height="55" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                                </svg>
                                <%end%>
                            </a>

                            <ul class="dropdown-menu dropdown-menu-end">
                                <% if !current_user.admin?%>
                                    <li><a class="dropdown-item" href="<%=guardarobas_path(current_user.id)%>">Wardrobe</a></li>
                                <%end%>
                                <% if current_user.creat?%>
                                    <li><a class="dropdown-item" href="<%=creator_path(current_user.creator_id)%>">Show Profile</a></li>
                                <%end%>
                                <%- if !current_user.admin? %>
                                    <li><a class="dropdown-item" href="<%=users_personalInfo_path%>">Avatar</a></li>
                                <%end%>
                                <%if current_user.admin? %>
                                    <li><a class="dropdown-item" href="<%=admin_path(current_user.id)%>">Manage Accounts</a></li>
                                <%end%>
                                <li><%= link_to 'Log Out', destroy_user_session_path,data: {turbo_method: :delete}, class:"dropdown-item"%></li>
                            </ul>
                        </div>
                    </div>
                <%else%>
                    <div class = "profile-pic">
                        <div class ="dropdown">
                            <a href="#" data-bs-toggle="dropdown" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="55" height="55" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                                </svg>
                            </a>

                            <ul class="dropdown-menu dropdown-menu-end">
                                <% if !current_user.admin?%>
                                    <li><a class="dropdown-item" href="<%=guardarobas_path(current_user.id)%>">Wardrobe</a></li>
                                <%end%>
                                <% if current_user.creat?%>
                                    <li><a class="dropdown-item" href="<%=creator_path(current_user.creator_id)%>">Show Profile</a></li>
                                <%end%>
                                <%- if !current_user.admin? %>
                                    <li><a class="dropdown-item" href="<%=users_personalInfo_path%>">Avatar</a></li>
                                <%end%>
                                <%- if current_user.admin? %>
                                    <li><a class="dropdown-item" href="<%=admin_path(current_user.id)%>">Manage Accounts</a></li>
                                <%end%>
                                <li><%= link_to 'Log Out', destroy_user_session_path,data: {turbo_method: :delete}, class:"dropdown-item"%></li>
                            </ul>

                        </div>
                    </div>
                <%end%>
            <%else%>
                <a href="<%=new_user_session_path%>">
                    <button class = "btn btn-light login-btn">Login</button>
                </a>
            <%end%>

            <a href="<%=search_path%>" class = "search-btn">     <!-- Da rivedere -->
                <button class = "btn btn-light ">Search...
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                    </svg>
                </button>
            </a>

            
        </div>
    </nav>



<p style="color: green"><%= notice %></p>

<h1>&nbsp;<%= current_user.username%>'s Wardrobe</h1>
<br>
<div class = "selection">
    &nbsp;&nbsp;<button class="btn disabled" id="capo-btn">Show capos</button>
    <button class="btn" id = "outfit-btn">Show outfits</button>
</div>

<div id="testo">
    <div id="guardarobas">
    
    <table >
        <% @guardarobas.each do |guardaroba| %>
        <div id="testo2" class = "capo">
            <%= image_tag(guardaroba.immagine_capo, size: "130",class: "capo-img") %><div id="testo3"><br><%=link_to "Buy on #{guardaroba.sito}", guardaroba.url%><br><br><%= button_to "Remove this item", guardaroba, method: :delete %></div>
        </div>
        <br>
        <% end %>
    </table>
     </div>
</div>

<div id="testo3">
<div class = "outfit2">
    
        <% @outfits.each do |outfit|%>
            <div class="card text-center outfit followed" id = "<%=outfit.id%>">
                        <div class="card-header">
                            <div class = "profile-pic">
                                <a href = "<%=creator_path(outfit.creator.id)%>">
                                    <% if outfit.creator.user.avatar.attached?  %>
                                        <img data-enlargable class = "avatar" src="<%=(url_for(outfit.creator.user.avatar))%>">
                                    <%else%>
                                        <svg xmlns="http://www.w3.org/2000/svg" width="55" height="55" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                                        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                                        <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                                    </svg>
                                    <%end%>
                                </a>
                                <p><%=outfit.creator.user.username%></p>
                            </div>

                            <div class = "outfit-name">
                                <p><%=outfit.name%></p>
                            </div>

                        </div>

                        <div class="card-body"> <!--Inserire lo slider -->
                            <div id = "carousel<%=outfit.id%>" class = "carousel slide" data-ride="carousel">
                                <div class = "carousel-inner">
                                    <% outfit.capos.each_with_index do |capo,index| %>
                                        <div class = "carousel-item <%="active" if index == 0%>">

                                            <img class="w-50 p-2" src = <%=url_for(capo.immagine)%>>
                                            <div class="testo-bordato">
                                            <div class="carousel-caption d-none d-md-block">
                                                <h6><%=capo.nome%></h6>
                                            </div>
                                            </div>

                                        </div>
                                    <%end%>
                                </div>

                                <a class="carousel-control-prev" href="#carousel<%=outfit.id%>" role="button" data-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Previous</span>
                                </a>
                                <a class="carousel-control-next" href="#carousel<%=outfit.id%>" role="button" data-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </div>
                        </div>

                        <div class="card-footer text-muted">
                            <div class = "show-outfit">
                                <a href = "<%=show_outfit_path(outfit.id)%>">Show details</a>
                                <%= button_to "Remove this item",guardaroba_remove_outfit_path(outfit.id),method: :post %>
                            </div>
                        </div>
                    </div>
                    <br>
                    <br>
        <%end%>
   
    
</div>
</div>
</body>
</html>

myFashionCloset/app/views/guardarobas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @guardaroba %>

<div>|
  <%= link_to "Back to guardarobas", guardarobas_path %>

  <%= button_to "Destroy this guardaroba", @guardaroba, method: :delete %>
</div>